In [3]:
import os

text = []
for filename in os.listdir("training_material"):
    with open(os.path.join("training_material", filename), "r") as f:
        text.append(f.read())

joined_text = " ".join(text)

In [4]:
print(len(joined_text))

129394


In [5]:
# Get unique characters that occur in the dataset
chars = sorted(list(set(joined_text)))  # set() removes duplicates
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 _·⿰⿱⿳、。《》「」㿉㿗䈽䏶䐈䐜䘌䘒䘓䬪䵟一丁七丈三上下不且世丙丞並中丰串丸丹主乃久之乍乎乏乖乘乙九也乳乾亂了予事二云互五井亟亡亢交亦亨京亭亮人仁仆今介仍仕他付仙代令以仰仲任伍伏伐休伯伸伺似佃但佇位低住佐佑何佗余佛作佩佳併使來例供依侯侵便促俗保俞信修俯俱倉個倍倒倘候倚借倦倫值假偉偏偑偕停健側偶偽備傢催傳傷傾僅僕僚僧僭僮僵價僻儒優兀允元兄充先光克免兒兔兜入內全兩八公六兮共其具典兼再冒冠冬冰冶冷冽准凋凌凍凝凡凰凹出刀分切刈刑列初別利刪刮到制刷刺刻則剉削剋前剔剖剛剜剝割劇劈劉劑力功加劣助努劫勁勉勒勔動勝勞勢勺勻勾勿包化北匙匪匯匱十千升午半卑卒協南博卜占危即卵卷卻卿厚原厥厭厲去參又叉及友反叔取受叢口古句只叫可台叱史右司吃各吅合吉同名后吏吐向君吞吟否含吮吳吸吹吼吾呃呆告周味呵呷呻呼命咀咂和咎咒咨咬咯咳咸咽哀品哉哮哺哽唇唐唧唯唾問啖啜啞啟啼啾善喉喎喘喙喚喜喝喪單喻嗄嗅嗇嗌嗜嗣嗽嘆嘈嘉嘔嘗嘯嘴噀噁噎噓噙噤噦器噫噯噴嚏嚥嚨嚮嚴嚼囊囚四回因困固國圍園圓圖團土在圭地均坐坑坡坤坦坩坼垂垢垣埋城域執培堂堅堤堪塊塌塗塞填塵境墜增墟墨墮壁壅壑壓壙壞士壬壯壺壽夏夕外多夜夢大天太夫夭央失夷夾奄奇奈奉奏奔套奠奧奪奭女奴奸奼好如妃妄妊妒妙妝妨妻始姑姜威娠娥娶婆婉婢婦媒媚媾嫌嫩嬌嬰子孔孕字存孟孤孩孫學宅守安宋完宏宗官定宛宜客宣室宦宮害家容宿寄密寇富寐寒寓察寡寢實寧審寫寬寰寵寶寸寺封射將專尉尊尋對導小少尖尚尤就尺尾尿局屁居屈屋屍屎屏屑展屢履屬山岐岩岸峭峰峻崇崔崖崩嵇嵐嵩嶺巔川州巡工左巧巨差己已巳巴巷巽市布希帖帚帛帝帥師席帶常幣干平年幸幹幼幽幾床序底庚府度座庭庵庶康庸廉廓廟廢廣廩廬廳延廷建廿弊式弓引弗弘弛弟弦弱張強彈彌彎彘形彥彰影役彼往待後徐徑徒得從御復循微徵德徹徽心必忌忍志忘忠忡忤快念忽忿怒怔思怠急性怪怯恃恍恐恙恚恣恭息悅悉悍悟患悲悵悶悸情惆惋惑惚惜惟惠惡惱想愁愈意愚愛感慄慈慎慓慘慢慣慧慨慮慶慾憂憊憎憒憨憫憶憹應懊懣懦懶懷懸懼懿戊戎成我戒或戟截戰戴戶房所扁扇手才扎打托扣扦扶承技把抑投折抱抵抹抽拈拌拒拔拘拙招拜拭拯拱拳拷拾持指按挑挺挼挾捉捕捶捷捻掃授掉掌掐排掘掛掠採探掣接控推措揀揉提插揚換握揩揭揮援損搏搐搓搖搗搜搦搽摘摩摻撥撩撫撬撮撲撼擁擂擇擊擎擒擔擘據擦擯擴擾攘攙攝攢攣攤攪支收改攻放故效敏救敕敗教敢散敵敷數斂斃斆文斌斑斕斗料斛斜斟斤斥斧斬斯新斷方於施旁旃旅旋族既日旦旨早旬旱旺昂昌明昏易昔星春昧是時晉

In [6]:
# Create a ampping from characters to integers
stoi = { char:index for index, char in enumerate(chars) }
itos = { index:char for index, char in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s]  # convert string to list of integers
decode = lambda l: ''.join([itos[i] for i in l])  # convert list of integers to string

print(encode("甘草"))
print(decode(encode("甘草")))

[1480, 2078]
甘草


In [9]:
# Let's encode the entire dataset, then store in a torch.Tensor

import torch
data = torch.tensor(encode(joined_text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:100])


torch.Size([129394]) torch.int64
tensor([1355, 1925, 2890,  990, 1615,    0,    0, 1480, 2060, 2843,  658,    8,
         180, 1925, 1819, 2890, 2648, 2741, 1400,    8, 1231,   24,  212, 1615,
        1520, 2890,  941, 1031, 1217,  990,   45,  318,    8,  292, 1022, 2891,
        1606, 1961, 1778, 2888, 1639,  533, 1681,  174,  613, 1961,    8,  981,
        2106, 1022, 2891,  990, 1615, 1481,  973, 2860, 2396, 2890,  110, 1064,
        1231, 2727, 2741, 2889,    8,    0,    0, 1435,  506, 2767, 2457, 1217,
         990,    8,  902, 1662, 1386,    8,  773,  481, 2855,   75,    8,    1,
           2, 1775, 2890, 1660,   53,    2,    0,    0, 2308, 1959, 1283, 1936,
           0,    0, 1480, 1269])


In [8]:
n = int(0.9 * len(data))
train_data = data[:n]
val_data = data[n:]

In [10]:
block_size = 8
train_data[:block_size+1]


tensor([1355, 1925, 2890,  990, 1615,    0,    0, 1480, 2060])

In [11]:
x = train_data[:block_size]
y = train_data[1:block_size+1]

for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"Context: {context}, target: {target}")

Context: tensor([1355]), target: 1925
Context: tensor([1355, 1925]), target: 2890
Context: tensor([1355, 1925, 2890]), target: 990
Context: tensor([1355, 1925, 2890,  990]), target: 1615
Context: tensor([1355, 1925, 2890,  990, 1615]), target: 0
Context: tensor([1355, 1925, 2890,  990, 1615,    0]), target: 0
Context: tensor([1355, 1925, 2890,  990, 1615,    0,    0]), target: 1480
Context: tensor([1355, 1925, 2890,  990, 1615,    0,    0, 1480]), target: 2060


## Batch the predicted output
Batch the predicted output from the tensor so that we get a xb that is the context and xy is the predicted output

In [12]:
torch.manual_seed(1337)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

# sample the batch
# each chunk of xb is a set of the training data
# each chunk of yb is the next word in the training data
xb, yb = get_batch('train') 
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

inputs:
torch.Size([4, 8])
tensor([[ 479,  271, 1534, 1811, 2890, 1950,  452,  506],
        [1350, 2890, 1204, 2669, 1900,  949, 2890,  338],
        [2002, 2006,   31,  573,    8, 1963, 1898, 2890],
        [1204,  243, 2650, 1598, 2890, 1264,  390,  243]])
targets:
torch.Size([4, 8])
tensor([[ 271, 1534, 1811, 2890, 1950,  452,  506, 1648],
        [2890, 1204, 2669, 1900,  949, 2890,  338, 2178],
        [2006,   31,  573,    8, 1963, 1898, 2890, 1977],
        [ 243, 2650, 1598, 2890, 1264,  390,  243, 1645]])
----
when input is [479] the target: 271
when input is [479, 271] the target: 1534
when input is [479, 271, 1534] the target: 1811
when input is [479, 271, 1534, 1811] the target: 2890
when input is [479, 271, 1534, 1811, 2890] the target: 1950
when input is [479, 271, 1534, 1811, 2890, 1950] the target: 452
when input is [479, 271, 1534, 1811, 2890, 1950, 452] the target: 506
when input is [479, 271, 1534, 1811, 2890, 1950, 452, 506] the target: 1648
when input is [1350] th

In [13]:
print(xb) # our input to the transformer

tensor([[ 479,  271, 1534, 1811, 2890, 1950,  452,  506],
        [1350, 2890, 1204, 2669, 1900,  949, 2890,  338],
        [2002, 2006,   31,  573,    8, 1963, 1898, 2890],
        [1204,  243, 2650, 1598, 2890, 1264,  390,  243]])


In [14]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)  - unscaled score for each token
        
        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss
    
    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


torch.Size([32, 2896])
tensor(8.2181, grad_fn=<NllLossBackward0>)

那布老箕菖撲擒程廉包倘洽蝨恃待論乎蒿鶡熾陳響蛛鼓口準改腦劣坦內闕戴互直狾詣肭衄騫南宮坦非啼見拱土逐鈴浴蚺荽足揉欣令腫虧敗至六蠟罕貘駱糯鶡嚥徵篆媚釐戎駛旨江麥雜百盂佃醜遊忽幸鴟醴麝料癜偑咸拭拒蓉興陶枇百
